export 'package:firebase_core/firebase_core.dart';
export 'package:flutter/material.dart';
export 'package:get/get.dart';
export 'package:physio_digital/firebase_options.dart';
export 'package:physio_digital/repository/product_repository.dart';
export 'package:physio_digital/repository/therapist_repository.dart';
export 'package:physio_digital/services/auth/auth_gate.dart';
export 'package:physio_digital/bindings/registration_binding.dart';
export 'package:physio_digital/controllers/home_controller.dart';
export 'package:physio_digital/themes/light_mode.dart';
export 'package:physio_digital/view/clinics/clinic.dart';
export 'package:physio_digital/view/home/home_page.dart';
export 'package:physio_digital/view/posts/list_posts.dart';
export 'package:physio_digital/view/products/listproduct/product_list_page.dart';
export 'package:physio_digital/view/profile/user_profile.dart';
export 'package:physio_digital/view/therapists/listTherapist/list_therapist_controller.dart';

export 'package:physio_digital/model/product/product.dart';
export 'package:physio_digital/view/home/buttom_bar.dart';